#!/bin/bash
scsrs="--------------------------------------------->8" 
notes="1 1"
for (( i = 2; i <= $1; ++i )); do notes="$notes\n$i $i"; done
until awk '{ if($1 == $3) {exit 1}}' <(echo "$cutnotes")
do
  shufnotes="$(echo -e "$notes" | sort -R)"
  cutnotes="$(paste <(echo -e "$notes") <(echo -e "$shufnotes"))"
done
awk -v scsrs="$scsrs" '
  BEGIN {print scsrs}
  {printf "You are No %03d and you gift No %03d\n%s\n", $1, $3, scsrs }
' <(echo "$cutnotes")
